package com.ite.authservice.entities;

public enum EPermission {
    LOGOUT,
    UPDATE_ACCOUNT_STATUS,
    UPDATE_ACCOUNT_INFO,
    UPDATE_ANOTHER_ACCOUNT_INFO,
    SEARCH_PAYMENT_ORDER,
    VIEW_PAYMENT_ORDER_DETAIL,
    REFUND_ORDER,
    SEARCH_REFUND_ORDER,
    VIEW_REFUND_ORDER_DETAIL,
    MANAGE_PERMISSION,
}
